actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
coverage:
    enabled: true
    include:
      - src/*
    exclude:
      - tests/_support/_generated/*
      - src/config/*
      - src/icons/*
      - src/migrations/*
      - src/templates/*
      - src/translations/*
      - src/migration.php.template
params:
  - env
modules:
  config:
    Yii2:
      configFile: 'tests/_craft/config/test.php'
  enabled:
    - Db:
        dsn: 'mysql:host=db;dbname=database;'
        user: 'root'
        password: 'root'
        dump: 'tests/_data/base_install.sql'
        populate: true
        cleanup: true
        reconnect: true