dateModified: 1555703339
email:
  fromEmail: abry.rath@union.co
  fromName: Sandbox
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  984edaed-d631-4376-8079-2ef989f29f92:
    name: Common
plugins:
  geolocation:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
siteGroups:
  2b1b5b7a-53fe-40a5-963f-797a5744ec17:
    name: Sandbox
sites:
  6c475cf7-1220-45d3-9d42-304033f97e72:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Sandbox
    primary: true
    siteGroup: 2b1b5b7a-53fe-40a5-963f-797a5744ec17
    sortOrder: 1
system:
  edition: solo
  name: Sandbox
  live: true
  schemaVersion: 3.1.26
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
